# Encoder enabled
CONSOLE_ENABLE = no
COMMAND_ENABLE = no

ENCODER_MAP_ENABLE = yes
MOUSEKEY_ENABLE = no
EXTRAKEY_ENABLE = no
SPACE_CADET_ENABLE = no
GRAVE_ESC_ENABLE = no
MAGIC_ENABLE = no

RGB_MATRIX_ENABLE = yes
LTO_ENABLE = yes
