# Encoder enabled
CONSOLE_ENABLE = no
COMMAND_ENABLE = no

ENCODER_MAP_ENABLE = yes
MOUSEKEY_ENABLE = yes
EXTRAKEY_ENABLE = no
SPACE_CADET_ENABLE = no
GRAVE_ESC_ENABLE = no
MAGIC_ENABLE = no
OS_DETECTION_ENABLE = yes

RGB_MATRIX_ENABLE = yes
TAP_DANCE_ENABLE = yes
LTO_ENABLE = yes
DEFERRED_EXEC_ENABLE = yes

# custom behavior
SUPER_ALT_TAB_ENABLE = no
OS_SWAP_CMD_KEY_ENABLE = no

SRC += dances.c
SRC += os_swap.c
